[package]
name = "exr_thumbnailer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
exr = "1.7.2"
image = "0.25.1"
rayon = "1.10.0"
