[package]
name = "exr-to-tiff-converter"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
exr = "1.73"
rayon = "1.8"
tiff = "0.9"

[[bin]]
name = "exr-to-tiff-converter"
path = "src/main.rs"