[package]
name = "exruster_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
exr = "1.73"
image = "0.24"
rayon = "1.7"
